<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<OutputType>Library</OutputType>
		<RootNamespace>TripMind.Infrastructure</RootNamespace>
		<UserSecretsId>8698b3ee-10ca-44ba-8c7e-3eae9d6d137e</UserSecretsId>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\TripMind.Domain\TripMind.Domain.csproj" />
		<ProjectReference Include="..\TripMind.Application\TripMind.Application.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.7">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.7" />
		<PackageReference Include="Google.Apis.Auth" Version="1.68.0" />
		<PackageReference Include="CloudinaryDotNet" Version="1.26.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.3.1" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="7.3.1" />

		<PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />

		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="8.0.7" />
	</ItemGroup>
</Project>
